Dockerfile, OdooStock-Dockerfile, prod-docker-compose.yml
- switch default dockerfile to be bitnami image to work in kubernetes
=> bitnami image

add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/views/hr_employee_views.xml, add-ons/hr_modifier/views/hr_job_views.xml, docker-compose.yml
- Made unnecessary fields in job view  invisible 
- added environment variable to compose to set which port compose should be forwarded too.
=> remove extra fields in job views

add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/models/__init__.py, add-ons/hr_modifier/models/hr_classification.py, add-ons/hr_modifier/models/hr_employee.py, add-ons/hr_modifier/models/hr_employee_base.py, add-ons/hr_modifier/models/hr_employee_public.py, add-ons/hr_modifier/security/ir.model.access.csv, add-ons/hr_modifier/views/hr_employee_classification_views.xml, add-ons/hr_modifier/views/hr_employee_views.xml, add-ons/hr_modifier/views/hr_views.xml
closes https://github.com/gcdevops/HRWhiteListing/issues/80
closes https://github.com/gcdevops/HRWhiteListing/issues/65
- Added all custom fields
- added employee classification table and view for user control of GoC classifications
=> adding custom fields

add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/security/hr_security.xml, add-ons/hr_modifier/security/ir.model.access.csv, add-ons/hr_modifier/views/hr_employee_public_views.xml, add-ons/hr_modifier/views/hr_employee_views.xml, add-ons/hr_modifier/views/hr_views.xml
resolves https://github.com/gcdevops/HRWhiteListing/issues/85
resolves https://github.com/gcdevops/HRWhiteListing/issues/64
=> added user role and modified public view

add-ons/hr_modifier/models/__init__.py, add-ons/hr_modifier/models/hr_employee_public.py, add-ons/hr_modifier/security/hr_security.xml, add-ons/hr_modifier/security/ir.model.access.csv, add-ons/hr_modifier/views/hr_employee_public_views.xml
- added edit access to public view so that managers can add employees to their team
=> add edit access to manager field

docker-compose.yml, servers.json
- Add pgAdmin + connection config (just need to enter "odoo" db password when prompted)
- Build is not needed anymore
- All we need to do is **docker-compose up -d**
=> Improve Docker Compose

add-ons/hr_modifier/views/hr_views.xml
resolves https://github.com/gcdevops/HRWhiteListing/issues/124
resolves https://github.com/gcdevops/HRWhiteListing/issues/62
Managers now have access to configurations
=> enabled configuration

add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/static/src/systray.xml, add-ons/hr_modifier/static/src/xml/chatter.xml, add-ons/hr_modifier/views/hr_employee_views.xml, add-ons/hr_modifier/views/mail_channel_views.xml
- Remove **Discussions** top right button
- Remove **Send message** and **Followers** bottom of profiles
- Remove **Discuss** menu item
- Remove **Launch Plan** button top of profiles
=> Clean user view

add-ons/hr_modifier/models/hr_employee.py, add-ons/hr_modifier/views/hr_employee_views.xml
resolves https://github.com/gcdevops/HRWhiteListing/issues/129
- add both option to remote connection tool field
- fix job field not showing jobs
=> add both option and fix job field

scripts/import.py
Did some light refactoring but only to the departments import so as to leave you the rest 
- added the use of environment variables to get credentials 
- removed code repetition 
- used csv DictReader so that the script does not break if for example there is no empty Translation column
=> light refactoring

add-ons/hr_modifier/models/hr_employee.py, add-ons/hr_modifier/models/hr_employee_base.py, add-ons/hr_modifier/models/hr_employee_public.py, add-ons/hr_modifier/views/hr_employee_public_views.xml, add-ons/hr_modifier/views/hr_employee_views.xml
resolves https://github.com/gcdevops/HRWhiteListing/issues/159
resolves https://github.com/gcdevops/HRWhiteListing/issues/164
=> Update public fields

add-ons/hr_modifier/i18n/fr_CA.po, add-ons/hr_modifier/views/hr_employee_views.xml
The warning about protected information has been removed.
=> removed the warning message in the view and translation

odoo.conf
https://github.com/gcdevops/HRWhiteListing/issues/215
=> Disable database access by default

add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/static/src/css/employee_views.css, add-ons/hr_modifier/views/hr_employee_public_views.xml, add-ons/hr_modifier/views/hr_employee_views.xml
resolves https://github.com/gcdevops/HRWhiteListing/issues/79
=> Resize left side panel

add-ons/hr_modifier/static/src/js/base_view.js, add-ons/hr_modifier/views/hr_employee_views.xml
resolves  gcdevops/HRWhiteListing#204
=> Remove the archive action

add-ons/hr_modifier/views/hr_employee_views.xml
Close https://github.com/gcdevops/HRWhiteListing/issues/236
=> Make Department a required field

add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/static/src/css/employee_views.css, add-ons/hr_modifier/static/src/js/language_toggle.js, add-ons/hr_modifier/static/src/xml/language_toggle.xml, add-ons/hr_modifier/views/assets.xml
resolves https://github.com/gcdevops/HRWhiteListing/issues/207
How to test
- make sure en_US or en_CA is active 
- make sure fr_FR or fr_CA is active 
- press the button to switch between languages
=> language toggle

add-ons/hr_modifier/views/hr_employee_public_views.xml, add-ons/hr_modifier/views/hr_employee_views.xml
**My Team** and **Public Directory** sections will now have a corresponding header
=> Update section headers

add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/static/src/js/base_view.js, add-ons/hr_modifier/static/src/xml/custom_filter_add.xml, add-ons/hr_modifier/static/src/xml/custom_group_add.xml
Resolves https://github.com/gcdevops/HRWhiteListing/issues/277
=> Added icons for custom filter and group buttons

add-ons/hr_modifier/models/hr_department.py, add-ons/hr_modifier/models/res_users.py, add-ons/hr_modifier/views/hr_department_views.xml, add-ons/hr_modifier/views/hr_employee_public_views.xml, add-ons/hr_modifier/views/hr_employee_views.xml, add-ons/hr_modifier/views/hr_views.xml
https://github.com/gcdevops/HRWhiteListing/issues/281
=> Rename Department to Team

add-ons/hr_modifier/models/hr_skills.py, add-ons/hr_modifier/views/hr_skills.xml, add-ons/hr_modifier/views/hr_views.xml
https://github.com/gcdevops/HRWhiteListing/issues/280
=> Remove Skill Levels

add-ons/hr_modifier/views/hr_department_views.xml, add-ons/hr_modifier/views/hr_employee_public_views.xml, add-ons/hr_modifier/views/hr_employee_views.xml, add-ons/hr_modifier/views/hr_plan_views.xml
https://github.com/gcdevops/HRWhiteListing/issues/285
=> Remove Archived search filter

add-ons/hr_modifier/views/assets.xml
Moved the script in assets.xml. I'm not sure why it stopped working in the first place though.
=> Fixing the language toggle

add-ons/hr_modifier/models/hr_job.py, scripts/import.py
Master promote
1. Readme file changed added badges
2. Turn on db export
=> Promote to master

odoo.conf
=> Undo db export

add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/models/__init__.py, add-ons/hr_modifier/models/hr_branch.py, add-ons/hr_modifier/models/hr_employee_base.py, add-ons/hr_modifier/security/ir.model.access.csv, add-ons/hr_modifier/views/hr_employee_branch_views.xml, add-ons/hr_modifier/views/hr_employee_views.xml, add-ons/hr_modifier/views/hr_views.xml
Creates a drop down in the employee view and a separate tree/form view for the branches.
=> added branch field

add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/static/src/js/user_menu.js, add-ons/hr_modifier/static/src/xml/user_menu.xml, add-ons/hr_modifier/views/assets.xml
Resolves [gcdevops/HRWhiteListing/issues/218](https://github.com/gcdevops/HRWhiteListing/issues/218)
=> Removed Odoo Account and Preferences from User Menu

add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/static/src/css/employee_views.css, add-ons/hr_modifier/static/src/js/menu.js, add-ons/hr_modifier/static/src/xml/menu.xml, add-ons/hr_modifier/views/assets.xml
Very simple change that I figured I'd put up while I am working on the nav indicator. @jaysonmc do you want me to change the purple hover on nav menu items to white? Or leave it as is?
=> Make nav background black to be closer to GC look and feel

add-ons/hr_modifier/i18n/fr_CA.po
https://github.com/gcdevops/HRWhiteListing/issues/307
**Note:** If you wish to test, you need to start from an empty database (unless you found a way to update existing translations, I haven't ;-)
=> Improve FR translation

add-ons/hr_modifier/models/res_partner.py, add-ons/hr_modifier/views/res_partner_views.xml
https://github.com/gcdevops/HRWhiteListing/issues/311#event-3361526786
=> Add building type

add-ons/hr_modifier/models/res_partner.py, add-ons/hr_modifier/views/res_partner_views.xml
Reverts gcdevops/OdooDocker#121
Caused errors
```
2020-05-25 14:58:23,174 1 ERROR dts-covid odoo.sql_db: bad query: SELECT "res_partner"."id" as "id","res_partner"."name" as "name","res_partner"."display_name" as "display_name","res_partner"."date" as "date","res_partner"."title" as "title","res_partner"."parent_id" as "parent_id","res_partner"."ref" as "ref","res_partner"."lang" as "lang","res_partner"."vat" as "vat","res_partner"."website" as "website","res_partner"."comment" as "comment","res_partner"."credit_limit" as "credit_limit","res_partner"."active" as "active","res_partner"."employee" as "employee","res_partner"."function" as "function","res_partner"."type" as "type","res_partner"."street" as "street","res_partner"."street2" as "street2","res_partner"."zip" as …
```
=> Revert "Add building type"

add-ons/hr_modifier/static/src/js/abstract_web_client.js, add-ons/hr_modifier/views/assets.xml, add-ons/odoo_web_login/templates/webclient_templates.xml
https://github.com/gcdevops/HRWhiteListing/issues/306
=> Change page title to "Liste blanche RH | HR Whitelist"

add-ons/hr_modifier/views/hr_employee_views.xml
- switch region in search view to branch
=> switch region for branch field

add-ons/hr_modifier/static/src/css/employee_views.css
Resolves https://github.com/gcdevops/HRWhiteListing/issues/91
=> Added focus indicators for top level nav menu items

Dockerfile, add-ons/hr_modifier/__manifest__.py, add-ons/hr_modifier/models/__init__.py, add-ons/hr_modifier/models/res_building_type.py, add-ons/hr_modifier/models/res_partner.py, add-ons/hr_modifier/security/ir.model.access.csv, add-ons/hr_modifier/views/hr_views.xml, add-ons/hr_modifier/views/res_building_type_views.xml, add-ons/hr_modifier/views/res_partner_views.xml, docker-compose.yml, scripts/custom_entrypoint.sh
- Add building type
- Add upgrade command to docker image
**NOTE**: The volume data is currently under ROOT rights ever since we flipped it to that. Can't swap back to odoo user without errors on volume mount file permissions. 
So line should be uncommented once that addressed.
=> Building type page

add-ons/hr_modifier/views/hr_employee_public_views.xml, add-ons/hr_modifier/views/hr_employee_views.xml
resolves https://github.com/gcdevops/HRWhiteListing/issues/323
=> Reorder sidebar + add fields to public view
